#!/bin/sh

# Colored makepkg-like functions
msg_blue() {
  printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
  printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
  note "==> To enable the service, run:"
  note "    systemctl --user enable --now vicinae.service"
}

post_upgrade() {
  post_install
}
